kind = "DojoModel"
class_hash = "0x483e8d67aaebfc2f09c3d95f06d42ebe07606e2134893af501bb2b1a9167c5a"
original_class_hash = "0x483e8d67aaebfc2f09c3d95f06d42ebe07606e2134893af501bb2b1a9167c5a"
abi = "manifests/dev/abis/base/models/oasis_systems_actions_actions_moved.json"
name = "oasis::systems::actions::actions::moved"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "direction"
type = "Direction"
key = false
