kind = "DojoModel"
class_hash = "0x49cead30390551510a4342e118e526bfe1cecf9fdfc3a2a6a3badc2dbbd4fe4"
original_class_hash = "0x49cead30390551510a4342e118e526bfe1cecf9fdfc3a2a6a3badc2dbbd4fe4"
abi = "manifests/dev/abis/base/models/oasis_models_moves_moves.json"
name = "oasis::models::moves::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false

[[members]]
name = "can_move"
type = "bool"
key = false
