kind = "DojoModel"
class_hash = "0x2c4454597f70f63b6ca6ac75de75b989a14b3ca0a0b84d7b774b815ae9bd2b3"
original_class_hash = "0x2c4454597f70f63b6ca6ac75de75b989a14b3ca0a0b84d7b774b815ae9bd2b3"
abi = "manifests/dev/abis/base/models/oasis_models_moves_directions_available.json"
name = "oasis::models::moves::directions_available"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
