import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import { DojoProvider, Web3Provider } from '~/providers';
import '~/styles/globals.css';

import { Toaster } from '~/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={`font-sans ${GeistSans.variable}`}>
        <Web3Provider>
          <DojoProvider>{children}</DojoProvider>
        </Web3Provider>
        <Toaster />
      </body>
    </html>
  );
};

export default RootLayout;
